### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by githuan** [szorfein/Gentoo-ZFS#1]
## ZFS system > Create datasets > Add swap... (Step 4)

`# zfs create -V 4G -b $(getconf PAGESIZE) \
  -o compression=lze \
  -o logbias=throughput -o sync=always \
  -o primarycache=metadata -o secondarycache=none \
  -o com.sun:auto-snapshot=false zfsforninja/swap`

### Minor Issue
Typo: `compression=lze` I am sure you mean **zle**

## install gentoo > CFLAGS and other options (Step 6)
 
> Compile them, replace `march` with the result above.
>`# sed -i 1,/options\ enabled/d native.s`

sed: can't read native.s: No such file or directory

This is where I am stuck. I appreciate your guide. The layout is very nice.

**Comment by szorfein** [comment]
thx a lot for this issue.  
`zle` from `after.md` is now fix.  

Concerning CFLAGS. yes i have missed to compile the `native.cc` in the doc, sry for that.

    # gcc -fverbose-asm -march=native native.cc -S

Doc is update, thx. i hope you will go to the end :)

**Comment by szorfein** [comment]
i close, free to report any others issue. thx
