### ISSUE TITLE
COMMON_FLAGS="-fexceptions" seems to break things

### ISSUE THREAD

**Issue by aux-j** [szorfein/Gentoo-ZFS#2]
Hi,

Just a heads up, not sure if you know or not but as the title implies, putting  -fexceptions in COMMON_FLAGS seems to break things. I've had firefox and a few other things (vte3, not sure what else) not build because of it. Maybe put a little disclaimer up? :-)

Cheers,
_j

**Comment by szorfein** [comment]
Thanks you very much for this, i've updated the wiki. don't hesitate if you find something else :)
